package br.ufs.avisamed.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GestorHuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestorHuAllPropertiesEquals(GestorHu expected, GestorHu actual) {
        assertGestorHuAutoGeneratedPropertiesEquals(expected, actual);
        assertGestorHuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestorHuAllUpdatablePropertiesEquals(GestorHu expected, GestorHu actual) {
        assertGestorHuUpdatableFieldsEquals(expected, actual);
        assertGestorHuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestorHuAutoGeneratedPropertiesEquals(GestorHu expected, GestorHu actual) {
        assertThat(expected)
            .as("Verify GestorHu auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestorHuUpdatableFieldsEquals(GestorHu expected, GestorHu actual) {
        assertThat(expected)
            .as("Verify GestorHu relevant properties")
            .satisfies(e -> assertThat(e.getIdColaborador()).as("check idColaborador").isEqualTo(actual.getIdColaborador()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestorHuUpdatableRelationshipsEquals(GestorHu expected, GestorHu actual) {
        assertThat(expected)
            .as("Verify GestorHu relationships")
            .satisfies(e -> assertThat(e.getColaborador()).as("check colaborador").isEqualTo(actual.getColaborador()));
    }
}
